In [1]:
import pandas as pd
from datetime import datetime, timedelta

In [4]:
pd.set_option('display.max_colwidth', None)
df = pd.read_csv(r"../NasdaqSMT_Csv/OSMT_0x22-4.csv", lineterminator='\n', index_col='Date')

In [3]:
"""
타임스탬프 변환 파트
"""
df["Datetime"] = df["Seconds"].apply(lambda x: datetime.fromtimestamp(x))
df["Timestamp(Convert)"] = df["Datetime"].apply(lambda x: x.strftime('%H:%M:%S'))
df = df[['Time', 'Message Type', 'Protocol ID', 'Timestamp(Convert)', 'Channel Index', 'Seconds', 'Raw Data']]
df

,Time,Message Type,Protocol ID,Timestamp(Convert),Channel Index,Seconds,Raw Data
Date,,,,,,,
02/01,13:19:14,0x22,51,15:10:00,5,22200,22 33 05 00 00 56 B8
02/01,13:19:14,0x22,51,15:15:01,5,22501,22 33 05 00 00 57 E5
02/01,13:19:14,0x22,51,15:15:02,5,22502,22 33 05 00 00 57 E6
02/01,13:19:14,0x22,51,15:15:03,5,22503,22 33 05 00 00 57 E7
02/01,13:19:14,0x22,51,15:15:04,5,22504,22 33 05 00 00 57 E8
...,...,...,...,...,...,...,...
02/01,16:25:19,0x22,51,02:15:00,5,62100,22 33 05 00 00 F2 94
02/01,16:25:19,0x22,51,02:20:09,5,62409,22 33 05 00 00 F3 C9
02/01,16:25:19,0x22,51,02:20:11,5,62411,22 33 05 00 00 F3 CB
02/01,16:25:19,0x22,51,02:20:14,5,62414,22 33 05 00 00 F3 CE
02/01,16:25:19,0x22,51,04:00:35,5,68435,22 33 05 00 01 0B 53