In [4]:
import pandas as pd
from datetime import datetime, timedelta

In [5]:
df = pd.read_csv(r"/mdfsvc/fep/log/Smart/OSMT_0x33-3.csv", lineterminator='\n', index_col='Date')

In [11]:
"""
특정 Symbol 필터링
"""
###############################
# 원하는 Symbol명을 입력하세요. #
i_want_to_find = "AMZN"
###############################

result_table = df[df['Symbol'].str.contains(i_want_to_find)]
result_table

,Time,Message Type,Locate Code,Country Code,Currecny Code,MIC,Product Type,Symbol Length,Symbol,Root Symbol,Put/Call,Expiration Date,Strike Price,Parent Locate Code,Raw Data
Date,,,,,,,,,,,,,,,
02/07,16:53:11,0x33,23,US,USD,,1,4,AMZN,NaN,NaN,0,0.0,0,33 00 00 00 17 55 53 55 53 44 20 20 20 20 01 0...
02/07,16:53:11,0x33,24,US,USD,,23,5,1AMZN,NaN,NaN,0,0.0,23,33 00 00 00 18 55 53 55 53 44 20 20 20 20 17 0...
02/07,16:53:11,0x33,401,US,USD,,23,5,2AMZN,NaN,NaN,0,0.0,23,33 00 00 01 91 55 53 55 53 44 20 20 20 20 17 0...
02/07,16:53:11,0x33,2126,US,USD,,23,4,AMZN,NaN,NaN,0,0.0,23,33 00 00 08 4E 55 53 55 53 44 20 20 20 20 17 0...
02/07,16:56:54,0x33,23,US,USD,,1,4,AMZN,NaN,NaN,0,0.0,0,33 00 00 00 17 55 53 55 53 44 20 20 20 20 01 0...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
02/07,21:09:44,0x33,11588,,,,2,19,AMZN200821C02240000,AMZN,C,20210821,2240.0,1822,33 00 00 2D 44 20 20 20 20 20 20 20 20 20 02 1...
02/07,21:09:44,0x33,11589,,,,2,19,AMZN210219C03100000,AMZN,C,20220219,3100.0,1822,33 00 00 2D 45 20 20 20 20 20 20 20 20 20 02 1...
02/07,21:09:44,0x33,11590,,,,2,19,AMZN200821C02205000,AMZN,C,20210821,2205.0,1822,33 00 00 2D 46 20 20 20 20 20 20 20 20 20 02 1...
02/07,21:09:44,0x33,11591,,,,2,19,AMZN210219C02210000,AMZN,C,20220219,2210.0,1822,33 00 00 2D 47 20 20 20 20 20 20 20 20 20 02 1...
02/07,21:09:44,0x33,11592,,,,2,19,AMZN200821C03100000,AMZN,C,20210821,3100.0,1822,33 00 00 2D 48 20 20 20 20 20 20 20 20 20 02 1...

In [7]:
unique_codes = df['Locate Code'].unique()
unique_codes
result_tables = {}

for code in unique_codes:
     result_tables[code] = df[(df['Locate Code'] == code) | (df['Parent Locate Code'] == code)]

In [13]:
"""
특정 Code를 가진 종목 모두 확인하기
"""
########################################
# 원하는 Parente Locate Code를 입력하세요.
i_want_to_find = 1821
########################################

result_tables[i_want_to_find]

,Time,Message Type,Locate Code,Country Code,Currecny Code,MIC,Product Type,Symbol Length,Symbol,Root Symbol,Put/Call,Expiration Date,Strike Price,Parent Locate Code,Raw Data
Date,,,,,,,,,,,,,,,
02/07,16:53:11,0x33,1821,US,USD,,1,3,AEO,NaN,NaN,0,0.0,0,33 00 00 07 1D 55 53 55 53 44 20 20 20 20 01 0...
02/07,16:53:11,0x33,1822,US,USD,,23,3,AEO,NaN,NaN,0,0.0,1821,33 00 00 07 1E 55 53 55 53 44 20 20 20 20 17 0...
02/07,16:56:54,0x33,1821,US,USD,,1,3,AEO,NaN,NaN,0,0.0,0,33 00 00 07 1D 55 53 55 53 44 20 20 20 20 01 0...
02/07,16:56:54,0x33,1822,US,USD,,23,3,AEO,NaN,NaN,0,0.0,1821,33 00 00 07 1E 55 53 55 53 44 20 20 20 20 17 0...
02/07,16:58:41,0x33,1821,US,USD,,1,3,AEO,NaN,NaN,0,0.0,0,33 00 00 07 1D 55 53 55 53 44 20 20 20 20 01 0...
02/07,16:58:41,0x33,1822,US,USD,,23,3,AEO,NaN,NaN,0,0.0,1821,33 00 00 07 1E 55 53 55 53 44 20 20 20 20 17 0...
02/07,17:00:04,0x33,1821,US,USD,,1,3,AEO,NaN,NaN,0,0.0,0,33 00 00 07 1D 55 53 55 53 44 20 20 20 20 01 0...
02/07,17:00:04,0x33,1822,US,USD,,23,3,AEO,NaN,NaN,0,0.0,1821,33 00 00 07 1E 55 53 55 53 44 20 20 20 20 17 0...
02/07,20:01:47,0x33,1821,US,USD,,23,5,AMZA1,NaN,NaN,0,0.0,1819,33 00 00 07 1D 55 53 55 53 44 20 20 20 20 17 0...
02/07,20:19:45,0x33,1821,US,USD,,23,5,AMZA1,NaN,NaN,0,0.0,1819,33 00 00 07 1D 55 53 55 53 44 20 20 20 20 17 0...
02/07,20:20:54,0x33,1821,US,USD,,23,5,AMZA1,NaN,NaN,0,0.0,1819,33 00 00 07 1D 55 53 55 53 44 20 20 20 20 17 0...
02/07,20:26:28,0x33,1821,US,USD,,23,5,AMZA1,NaN,NaN,0,0.0,1819,33 00 00 07 1D 55 53 55 53 44 20 20 20 20 17 0...
02/07,20:31:37,0x33,1821,US,USD,,23,5,AMZA1,NaN,NaN,0,0.0,1819,33 00 00 07 1D 55 53 55 53 44 20 20 20 20 17 0...
02/07,20:36:19,0x33,1821,US,USD,,23,5,AMZA1,NaN,NaN,0,0.0,1819,33 00 00 07 1D 55 53 55 53 44 20 20 20 20 17 0...
02/07,20:45:52,0x33,1821,US,USD,,23,5,AMZA1,NaN,NaN,0,0.0,1819,33 00 00 07 1D 55 53 55 53 44 20 20 20 20 17 0...
02/07,20:47:06,0x33,1821,US,USD,,23,5,AMZA1,NaN,NaN,0,0.0,1819,33 00 00 07 1D 55 53 55 53 44 20 20 20 20 17 0...
02/07,20:48:58,0x33,1821,US,USD,,23,5,AMZA1,NaN,NaN,0,0.0,1819,33 00 00 07 1D 55 53 55 53 44 20 20 20 20 17 0...
02/07,20:49:43,0x33,1821,US,USD,,23,5,AMZA1,NaN,NaN,0,0.0,1819,33 00 00 07 1D 55 53 55 53 44 20 20 20 20 17 0...
02/07,20:58:05,0x33,1821,US,USD,,23,5,AMZA1,NaN,NaN,0,0.0,1819,33 00 00 07 1D 55 53 55 53 44 20 20 20 20 17 0...
02/07,20:58:18,0x33,1821,US,USD,,23,5,AMZA1,NaN,NaN,0,0.0,1819,33 00 00 07 1D 55 53 55 53 44 20 20 20 20 17 0...
02/07,21:00:17,0x33,1821,US,USD,,23,5,AMZA1,NaN,NaN,0,0.0,1819,33 00 00 07 1D 55 53 55 53 44 20 20 20 20 17 0...
02/07,21:00:33,0x33,1821,US,USD,,23,5,AMZA1,NaN,NaN,0,0.0,1819,33 00 00 07 1D 55 53 55 53 44 20 20 20 20 17 0...
02/07,21:00:36,0x33,1821,US,USD,,23,5,AMZA1,NaN,NaN,0,0.0,1819,33 00 00 07 1D 55 53 55 53 44 20 20 20 20 17 0...
02/07,21:04:46,0x33,1821,US,USD,,23,5,AMZA1,NaN,NaN,0,0.0,1819,33 00 00 07 1D 55 53 55 53 44 20 20 20 20 17 0...
02/07,21:04:54,0x33,1821,US,USD,,23,5,AMZA1,NaN,NaN,0,0.0,1819,33 00 00 07 1D 55 53 55 53 44 20 20 20 20 17 0...
02/07,21:05:06,0x33,1821,US,USD,,23,5,AMZA1,NaN,NaN,0,0.0,1819,33 00 00 07 1D 55 53 55 53 44 20 20 20 20 17 0...
02/07,21:06:37,0x33,1821,US,USD,,23,5,AMZA1,NaN,NaN,0,0.0,1819,33 00 00 07 1D 55 53 55 53 44 20 20 20 20 17 0...
02/07,21:09:34,0x33,1821,US,USD,,23,5,AMZA1,NaN,NaN,0,0.0,1819,33 00 00 07 1D 55 53 55 53 44 20 20 20 20 17 0...
02/07,21:09:44,0x33,1821,US,USD,,23,5,AMZA1,NaN,NaN,0,0.0,1819,33 00 00 07 1D 55 53 55 53 44 20 20 20 20 17 0...